# Generated by Django 3.2.4 on 2021-06-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demon_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Demon",
        ),
    ]
